import sys
from PyQt5.QtWidgets import (QDialog,QLabel,QApplication,QVBoxLayout,
                             QHBoxLayout,QTextBrowser)
import qdarkstyle
from PyQt5.QtGui import QIcon,QPixmap,QFont
from PyQt5.QtSql import QSqlQuery,QSqlDatabase


class GoodDetailDialog(QDialog):
    def __init__(self,GoodId,size,str1,str2,str3):
        super(GoodDetailDialog,self).__init__()
        self.good = GoodId
        self.size = size
        self.str1 = str1
        self.str2 = str2
        self.str3 = str3
        self.resize(800,600)
        self.setWindowTitle("myERP——商品详情")
        self.setWindowIcon(QIcon("./image/icon.png"))
        self.initUI()

    def initUI(self):
        self.db = QSqlDatabase.addDatabase("QSQLITE")
        self.db.setDatabaseName('./db/myERP.db')
        self.db.open()
        self.query = QSqlQuery()
        sql = "select * from goods where id = '%s'" %(self.good)
        self.query.exec_(sql)
        self.query.next()

        id = self.query.value(0)
        name = self.query.value(1)
        company = self.query.value(2)
        date = self.query.value(3)
        price = self.query.value(4)
        img = self.query.value(5)
        screen = self.query.value(6)
        CPU = self.query.value(7)
        GPU = self.query.value(8)
        advantage = self.query.value(9)
        disadvantage = self.query.value(10)

        self.labeltitle = QLabel(self)
        self.imagetitle = QPixmap()
        self.imagetitle.load(img)
        self.labeltitle.setFixedSize(350,250)
        self.labeltitle.setPixmap(self.imagetitle.scaled(self.labeltitle.width(), self.labeltitle.height()))
        self.h1box = QHBoxLayout()
        self.h1box.addStretch(1)
        self.h1box.addWidget(self.labeltitle)
        self.h1box.addStretch(1)

        self.idlabel = QLabel()
        self.idlabel.setText('商品编号：')
        self.idlabel.setFont(QFont("苏新诗柳楷繁", 13))
        self.idlabel_ = QLabel()
        self.idlabel_.setFont(QFont("苏新诗柳楷繁", 13))
        self.idlabel_.setText(id)
        self.pricelabel = QLabel()
        self.pricelabel.setText('商品价格：')
        self.pricelabel.setFont(QFont("苏新诗柳楷繁", 13))
        self.pricelabel_ = QLabel()
        self.pricelabel_.setFont(QFont("苏新诗柳楷繁", 13))
        self.pricelabel_.setText(str(price))
        self.h2box = QHBoxLayout()
        self.h2box.addStretch(1)
        self.h2box.addWidget(self.idlabel)
        self.h2box.addWidget(self.idlabel_)
        self.h2box.addStretch(1)
        self.h2box.addWidget(self.pricelabel)
        self.h2box.addWidget(self.pricelabel_)
        self.h2box.addStretch(1)

        self.namelabel = QLabel()
        self.namelabel.setText('商品名称：')
        self.namelabel.setFont(QFont("苏新诗柳楷繁", 13))
        self.namelabel_ = QLabel()
        self.namelabel_.setFont(QFont("苏新诗柳楷繁", 13))
        self.namelabel_.setText(name)
        self.h3box = QHBoxLayout()
        self.h3box.addStretch(1)
        self.h3box.addWidget(self.namelabel)
        self.h3box.addWidget(self.namelabel_)
        self.h3box.addStretch(1)

        self.companylabel = QLabel()
        self.companylabel.setText('上市日期：')
        self.companylabel.setFont(QFont("苏新诗柳楷繁", 13))
        self.companylabel_ = QLabel()
        self.companylabel_.setFont(QFont("苏新诗柳楷繁", 13))
        self.companylabel_.setText(date)
        self.h4box = QHBoxLayout()
        self.h4box.addStretch(1)
        self.h4box.addWidget(self.companylabel)
        self.h4box.addWidget(self.companylabel_)
        self.h4box.addStretch(1)

        self.screenlabel = QLabel()
        self.screenlabel.setText('屏幕：')
        self.screenlabel.setFont(QFont("苏新诗柳楷繁", 13))
        self.screenlabel_ = QLabel()
        self.screenlabel_.setFont(QFont("苏新诗柳楷繁", 13))
        self.screenlabel_.setText(screen)
        self.CPUlabel = QLabel()
        self.CPUlabel.setText('CPU：')
        self.CPUlabel.setFont(QFont("苏新诗柳楷繁", 13))
        self.CPUlabel_ = QLabel()
        self.CPUlabel_.setFont(QFont("苏新诗柳楷繁", 13))
        self.CPUlabel_.setText(CPU)
        self.h5box = QHBoxLayout()
        self.h5box.addStretch(1)
        self.h5box.addWidget(self.screenlabel)
        self.h5box.addWidget(self.screenlabel_)
        self.h5box.addStretch(1)
        self.h5box.addWidget(self.CPUlabel)
        self.h5box.addWidget(self.CPUlabel_)
        self.h5box.addStretch(1)

        self.GPUlabel = QLabel()
        self.GPUlabel.setText('GPU：')
        self.GPUlabel.setFont(QFont("苏新诗柳楷繁", 13))
        self.GPUlabel_ = QLabel()
        self.GPUlabel_.setFont(QFont("苏新诗柳楷繁", 13))
        self.GPUlabel_.setText(GPU)
        self.h6box = QHBoxLayout()
        self.h6box.addStretch(1)
        self.h6box.addWidget(self.GPUlabel)
        self.h6box.addWidget(self.GPUlabel_)
        self.h6box.addStretch(1)

        self.adlabel = QLabel()
        self.adlabel.setText('优点：')
        self.adlabel.setFont(QFont("苏新诗柳楷繁", 13))
        self.adtb = QTextBrowser()
        self.adtb.setText(advantage)
        self.adtb.setFixedSize(250,200)
        self.adtb.setFont(QFont("苏新诗柳楷繁", 12))
        self.disadtb = QTextBrowser()
        self.disadtb.setText(disadvantage)
        self.disadtb.setFixedSize(250,200)
        self.disadtb.setFont(QFont("苏新诗柳楷繁", 12))
        self.disadlabel = QLabel()
        self.disadlabel.setText('缺点：')
        self.disadlabel.setFont(QFont("苏新诗柳楷繁", 13))

        self.v1box = QVBoxLayout()
        self.v1box.addLayout(self.h1box)
        self.v1box.addLayout(self.h2box)
        self.v1box.addLayout(self.h3box)
        self.v1box.addLayout(self.h4box)
        self.v1box.addLayout(self.h5box)
        self.v1box.addLayout(self.h6box)

        self.v2box = QVBoxLayout()
        self.v2box.addStretch(1)
        self.v2box.addWidget(self.adlabel)
        self.v2box.addWidget(self.adtb)
        self.v2box.addStretch(1)
        self.v2box.addWidget(self.disadlabel)
        self.v2box.addWidget(self.disadtb)
        self.v2box.addStretch(1)


        self.htbox = QHBoxLayout()
        self.htbox.addStretch(1)
        self.htbox.addLayout(self.v1box)
        self.htbox.addStretch(1)
        self.htbox.addLayout(self.v2box)
        self.htbox.addStretch(1)

        self.vbox = QVBoxLayout()
        self.vbox.addStretch(1)
        self.vbox.addLayout(self.htbox)
        self.vbox.addStretch(1)

        if(self.size > 0):
            self.youlabel = QLabel()
            self.youlabel.setText('你可能还对以下商品感兴趣：')
            self.youlabel.setFont(QFont("苏新诗柳楷繁", 13))
            self.vbox.addWidget(self.youlabel)
            self.vbox.addStretch(1)

            self.hbbox = QHBoxLayout()
            self.hbbox.addStretch(1)

            self.db = QSqlDatabase.addDatabase("QSQLITE")
            self.db.setDatabaseName('./db/myERP.db')
            self.db.open()
            self.query = QSqlQuery()
            sql = "select * from goods where id = '%s'" % (self.str1)
            self.query.exec_(sql)
            self.query.next()
            img1 = self.query.value(5)
            name1 = self.query.value(1)

            self.labeltitle1 = QLabel(self)
            self.imagetitle1 = QPixmap()
            self.imagetitle1.load(img1)
            self.labeltitle1.setFixedSize(200,150)
            self.labeltitle1.setPixmap(self.imagetitle1.scaled(self.labeltitle1.width(), self.labeltitle1.height()))

            self.name1label = QLabel()
            self.name1label.setText(name1)
            self.name1label.setFont(QFont("苏新诗柳楷繁", 10))
            self.name1label.setFixedWidth(200)

            self.bbv1box = QVBoxLayout()
            self.bbv1box.addWidget(self.labeltitle1)
            self.bbv1box.addWidget(self.name1label)

            self.hbbox.addLayout(self.bbv1box)
            self.hbbox.addStretch(1)

            if(self.size > 1):
                sql = "select * from goods where id = '%s'" % (self.str2)
                self.query.exec_(sql)
                self.query.next()
                img2 = self.query.value(5)
                name2 = self.query.value(1)

                self.labeltitle2 = QLabel(self)
                self.imagetitle2 = QPixmap()
                self.imagetitle2.load(img2)
                self.labeltitle2.setFixedSize(200, 150)
                self.labeltitle2.setPixmap(self.imagetitle2.scaled(self.labeltitle2.width(), self.labeltitle2.height()))

                self.name2label = QLabel()
                self.name2label.setText(name2)
                self.name2label.setFont(QFont("苏新诗柳楷繁", 10))
                self.name2label.setFixedWidth(200)
                self.bbv2box = QVBoxLayout()
                self.bbv2box.addWidget(self.labeltitle2)
                self.bbv2box.addWidget(self.name2label)

                self.hbbox.addLayout(self.bbv2box)
                self.hbbox.addStretch(1)
                if(self.size > 2):
                    sql = "select * from goods where id = '%s'" % (self.str3)
                    self.query.exec_(sql)
                    self.query.next()
                    img3 = self.query.value(5)
                    name3 = self.query.value(1)

                    self.labeltitle3 = QLabel(self)
                    self.imagetitle3 = QPixmap()
                    self.imagetitle3.load(img3)
                    self.labeltitle3.setFixedSize(200, 150)
                    self.labeltitle3.setPixmap(
                        self.imagetitle3.scaled(self.labeltitle3.width(), self.labeltitle3.height()))

                    self.name3label = QLabel()
                    self.name3label.setText(name3)
                    self.name3label.setFont(QFont("苏新诗柳楷繁", 10))
                    self.name3label.setFixedWidth(200)

                    self.bbv3box = QVBoxLayout()
                    self.bbv3box.addWidget(self.labeltitle3)
                    self.bbv3box.addWidget(self.name3label)

                    self.hbbox.addLayout(self.bbv3box)
                    self.hbbox.addStretch(1)

            self.vbox.addLayout(self.hbbox)
            self.vbox.addStretch(1)

        self.setLayout(self.vbox)



if __name__ == '__main__':
    app = QApplication(sys.argv)
    app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())
    gooddetaildialogWindow = GoodDetailDialog("01",3,'02','03','04')
    gooddetaildialogWindow.show()
    sys.exit(app.exec_())